# Generated by Django 5.0 on 2023-12-11 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postform_image_postform_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postform',
            old_name='summary',
            new_name='author',
        ),
    ]
