# Generated by Django 5.0 on 2023-12-13 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_commentform_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
    ]
