# Generated by Django 5.0 on 2023-12-14 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postform',
            name='body',
        ),
        migrations.RemoveField(
            model_name='postform',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='postform',
            name='summary',
        ),
    ]
