# Generated by Django 5.0 on 2023-12-14 09:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_postform_body_remove_postform_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='postImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, default='no-image.png', null=True, upload_to='media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp', 'tiff'])])),
            ],
        ),
        migrations.DeleteModel(
            name='postForm',
        ),
    ]
