# Generated by Django 5.0 on 2023-12-17 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_remove_posttarget_author_remove_posttarget_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postabout',
            name='title',
        ),
    ]
