# Generated by Django 5.0 on 2023-12-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_postform_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postform',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
